# Generated by Django 4.1 on 2022-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
