# Generated by Django 4.1 on 2022-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='review',
            field=models.TextField(),
        ),
    ]
