# Generated by Django 4.1 on 2022-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_watchlist_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.DateField(),
        ),
    ]
